version: '3.8'
services:
  strapi:
    image: goramax/strapi:latest
    build: ./strapi_01
    container_name: burgerverse_strapi
    restart: unless-stopped
    ports:
      - 1337:1337

  front:
    image: goramax/front:latest
    build: ./front
    container_name: burgerverse_front
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - strapi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bvo.rule=Host(`bvo.maxime-malherbe.fr`)"
      - "traefik.http.routers.bvo.entrypoints=websecure"
      - "traefik.http.routers.bvo.tls=true"
      - "traefik.http.routers.bvo.tls.certresolver=myresolver"
    networks:
      - traefiknet
      
networks:
  traefiknet:
    external: true